version: '2'
services:
  compta-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/compta/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=compta
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
